name: 'lcov-action'
description: 'Action to run lcov'
branding:
    color: 'blue'
    icon: 'check-square'
inputs:
    gcov_path:
        description: 'Path to gcov'
        required: true
        default: '/usr/bin/gcov'
    remove_patterns:
        description: 'Remove patterns, comma separated'
        required: true
        default: ''
    output_lcov_info:
        description: 'Output lcov info file'
        required: true
        default: 'coverage.info'
    build_dir:
        description: 'Build directory (lcov -d)'
        required: true
        default: '.'
    base_dir:
        description: 'Base directory (lcov -b)'
        required: true
        default: '.'
runs:
    using: 'docker'
    image: 'docker://ghcr.io/danielealbano/lcov-action:v4'
